const {
  createChapterHeading,
  createSectionHeading,
  createSubSectionHeading,
  createBody,
  createBullet,
  createSubBullet,
  createCallout,
  createMatrixTable
} = require('./helpers');

function getChapter1() {
  const elements = [];

  elements.push(createChapterHeading('1', 'Industry Context, Problem Space & Strategic Imperative'));

  // 1.1 The Fragmented Wearable Ecosystem
  elements.push(createSectionHeading('1.1 The Fragmented Modern Wearable Ecosystem'));
  elements.push(createBody('Over the past decade, personal health telemetry has evolved from rudimentary step counters into sophisticated multi-sensor physiological monitors. Contemporary wearables—spanning the Fitbit Sense and Charge families, Google Pixel Watch series, and Wear OS hardware ecosystems—feature high-frequency photoplethysmography (PPG), dual-wavelength pulse oximetry (SpO2), electrodermal activity (cEDA) sensors, and multi-axis accelerometers.'));
  elements.push(createBody('Despite rapid advancements in wearable sensor hardware, the client software layer has severely lagged behind. End users are confronted with an increasingly fragmented, siloed, and frustrating digital health experience. Telemetry generated by the same physical human body is routinely scattered across disjointed proprietary ecosystems, disparate cloud backends, and poorly synchronized mobile client applications.'));

  elements.push(createCallout(
    'The Wearable Integration Paradox',
    'While modern sensors capture millions of biometric data points daily, less than 5% of this telemetry is transformed into actionable, longitudinal health intelligence. Users are inundated with raw, uncontextualized metrics that often contradict one another across different application screens.'
  ));

  // 1.2 Systemic Flaws in Stock Mobile Applications
  elements.push(createSectionHeading('1.2 Systemic Flaws in Stock Mobile Health Applications'));
  elements.push(createBody('A comprehensive technical audit of standard consumer wearable applications revealed four critical failure modes that severely diminish user engagement, trust, and health outcomes:'));

  elements.push(createSubSectionHeading('1.2.1 Severe Data Fragmentation and Cognitive Overload'));
  elements.push(createBody('Stock wearable applications compartmentalize interrelated physiological parameters into isolated sub-screens. Sleep stages are locked inside a dedicated sleep tab; resting heart rate is hidden within a cardiovascular drill-down; active minutes reside in an exercise log; and daily steps dominate the primary landing page. This fragmentation forces users to manually cross-reference distinct screens to answer basic physiological questions, such as whether a drop in resting heart rate correlates with increased deep sleep or reduced cardiovascular strain.'));

  elements.push(createSubSectionHeading('1.2.2 High Network Latency and Offline Frustration'));
  elements.push(createBody('The vast majority of stock fitness applications operate on a strictly online-dependent, client-server model. When a user opens the application in an environment with poor connectivity (e.g., transit tunnels, gyms, flight mode, or rural areas), the user interface defaults to spinning progress indicators, blocking modal alerts, or completely blank state placeholders. Raw biometric data previously downloaded is rarely persisted into an indexed, queryable local document store.'));

  elements.push(createSubSectionHeading('1.2.3 Battery Inefficiency and Uncontrolled Background Sync'));
  elements.push(createBody('Poorly optimized background synchronization services continuously poll cloud APIs without respecting exponential backoff or network availability states. This continuous polling rapidly exhausts mobile battery life and triggers aggressive operating system process termination (e.g., Android Doze mode and App Standby Buckets), leading to corrupted sync states and stale cached biometrics.'));

  elements.push(createSubSectionHeading('1.2.4 Proprietary "Black-Box" Recovery Scoring'));
  elements.push(createBody('Several commercial applications have introduced proprietary "readiness" or "recovery" scores. However, the mathematical formulation behind these numbers is almost universally treated as proprietary intellectual property and withheld from the user. When a user receives a score of "64" without transparent explanations regarding how sleep duration, heart rate variability (HRV), or prior-day training strain influenced that calculation, the metric ceases to provide actionable guidance and breeds user skepticism.'));

  // 1.3 The Biometric Integrity Crisis
  elements.push(createSectionHeading('1.3 The Biometric Integrity Crisis in Raw Sensor APIs'));
  elements.push(createBody('Perhaps the most insidious problem uncovered during our systems analysis is what we term the "Biometric Integrity Crisis." Consumer health APIs (such as raw REST endpoints) frequently emit mathematically misleading or uncalibrated values that degrade the user experience if displayed without intelligent client-side normalization.'));

  const anomalyHeaders = ['Biometric Dimension', 'Raw API Behavior / Anomaly', 'Physiological & Behavioral Impact', 'Mathematical Severity'];
  const anomalyRows = [
    [
      'Caloric Expenditure (BMR)',
      'Raw endpoints credit the full 24-hour Basal Metabolic Rate (~1,400 kcal) upfront at 00:00:01 AM.',
      'A user waking at 08:00 AM with only 30 physical steps is falsely told they have burned 1,430 kcal and completed 71% of their daily goal before eating breakfast or exercising.',
      'CRITICAL: Completely destroys user motivation and distorts energy balance calculations.'
    ],
    [
      'Sleep Duration vs Restfulness',
      'APIs record "Time in Bed" (e.g., 562 minutes) as total sleep, ignoring interspersed wakefulness.',
      'Users with fragmented, poor-quality sleep are credited with 9+ hours of rest, obscuring underlying sleep apnea, insomnia, or elevated sleep debt.',
      'HIGH: Obscures clinical sleep deficits and invalidates recovery assessments.'
    ],
    [
      'Sleep Date Attribution',
      'Overnight sleep spanning Day N (22:30) to Day N+1 (07:15) is timestamped to Day N (bedtime date).',
      'When the user wakes up on Day N+1 and checks their dashboard, the sleep card is empty ("No Sleep Recorded"), causing severe confusion and support tickets.',
      'HIGH: Destroys real-time morning utility and breaks circadian alignment.'
    ],
    [
      'Cardiovascular Sensor Outages',
      'When optical PPG sensors lose skin contact during intense exercise or charging, APIs return 0 BPM or NaN.',
      'Averages and trend lines crash to near-zero; user interfaces display alarming spikes or pathological bradycardia warnings.',
      'MODERATE: Causes acute user anxiety and distorts longitudinal rolling averages.'
    ],
    [
      'Intraday Telemetry Sparsity',
      'Minute-by-minute heart rate telemetry is frequently delayed or throttled by cloud sync quotas.',
      'Active Zone Minutes (AZM) calculators that strictly require intraday beat streams fail, reporting 0 AZM despite strenuous cardiovascular workouts.',
      'HIGH: Fails to reward cardiovascular training compliance.'
    ]
  ];
  elements.push(createMatrixTable(anomalyHeaders, anomalyRows, [20, 30, 35, 15]));

  // 1.4 Business, Clinical & Engineering Objectives
  elements.push(createSectionHeading('1.4 Business, Clinical & Engineering Objectives'));
  elements.push(createBody('To definitively resolve these systemic defects, the engineering team established a rigorous architectural charter governed by five non-negotiable tenets:'));

  elements.push(createBullet('Every physiological metric displayed on screen must be scientifically grounded, mathematically normalized against circadian pacing, and clinically contextualized against established medical benchmarks (e.g., American Heart Association cardiovascular zones).', '1. Uncompromising Biometric Truth: '));
  elements.push(createBullet('The mobile application must provide instant (sub-16ms) interactive rendering upon cold launch, utilizing an offline-first indexed document database that transparently synchronizes with cloud repositories in the background.', '2. Zero-Latency Offline-First Architecture: '));
  elements.push(createBullet('All recovery and readiness calculations must be deterministic, transparent, and accompanied by humanized, rule-based coaching insights explaining the exact physiological drivers behind daily scores.', '3. Open-Box Physiological Determinism: '));
  elements.push(createBullet('Personally Identifiable Health Information (PII) must be protected using hardware-backed cryptographic keystores on the physical device and strict path-level isolation rules in cloud databases, guaranteeing zero cross-tenant leakage.', '4. Military-Grade Privacy and Cryptographic Isolation: '));
  elements.push(createBullet('The entire codebase must achieve 100% test pass rates across static analyzers, unit tests, Cubit state machines, and repository mocks, backed by an automated CI/CD pipeline that compiles release-ready, optimized binaries.', '5. Enterprise Engineering Rigor: '));

  return elements;
}

module.exports = { getChapter1 };
