const {
  createChapterHeading,
  createSectionHeading,
  createSubSectionHeading,
  createBody,
  createBullet,
  createSubBullet,
  createCallout,
  createDiagramBlock,
  createFigure,
  createMatrixTable
} = require('./helpers');

function getChapter6() {
  const elements = [];

  elements.push(createChapterHeading('6', 'Deep-Dive Feature Modules & Presentation Engineering'));

  // 6.1 Dashboard Module
  elements.push(createSectionHeading('6.1 Dashboard Module: The Central Command Center'));
  elements.push(createBody('The Dashboard Screen (DashboardScreen) serves as the primary executive viewport. It condenses multi-dimensional physiological telemetry into an immediate, scannable visual hierarchy. The screen employs a CustomScrollView featuring sliver headers, physics-based pull-to-refresh, and staggered entrance micro-animations.'));

  const dashboardTree = 
`DashboardScreen (StatefulWidget / BlocConsumer<DashboardCubit, DashboardState>)
  |
  +---> Scaffold (Background: AppTheme.darkBackground)
          |
          +---> RefreshIndicator (Physics: AlwaysScrollableScrollPhysics)
                  |
                  +---> CustomScrollView
                          |
                          +---> SliverToBoxAdapter: _HeaderRow (Avatar, Greeting, SyncBadge)
                          |
                          +---> SliverToBoxAdapter: _ReadinessCard (Animated Radial Ring 0-100)
                          |
                          +---> SliverToBoxAdapter: _HabitStreakTracker (7 Day-Dots, Flame Icon)
                          |
                          +---> SliverToBoxAdapter: _HealthCoachBanner (Priority Alert Carousel)
                          |
                          +---> SliverPadding (EdgeInsets.all(16))
                          |       |
                          |       +---> SliverGrid (2-Column Responsive Matrix)
                          |               |-- _MetricCard (Steps: 10,482)
                          |               |-- _MetricCard (Calories: 648 kcal [Prorated])
                          |               |-- _MetricCard (Distance: 7.8 km)
                          |               |-- _MetricCard (Active Minutes: 42 min)
                          |               |-- _MetricCard (Heart Rate: 71 bpm [Historical Fallback])
                          |               |-- _MetricCard (Sleep: 8h 45m [Net Sleep Fallback])
                          |
                          +---> SliverToBoxAdapter: _StepVolumeBarChart (FL Chart BarChart)
                          |
                          +---> SliverToBoxAdapter: _WeeklyTrendCard (7-Day Comparative Delta)`;
  elements.push(createDiagramBlock(dashboardTree));

  elements.push(...createFigure(
    './assets/fig2_dashboard_overview.png',
    '6.1',
    'Master Health Dashboard Viewport — Displaying the Animated Daily Readiness Recovery Ring (89 Score), Habit Streak Compliance Tracker, and 6-Metric Health Card Grid with Dynamic Historical Fallbacks.'
  ));

  elements.push(createSubSectionHeading('6.1.1 The Hero Daily Readiness Card'));
  elements.push(createBody('Anchoring the top of the dashboard, the Readiness Card visualizes the user recovery state using a custom animated radial progress ring. The ring dynamically transitions between three thematic color palettes: Emerald Green (Optimal, 80–100), Amber Gold (Moderate, 60–79), and Rose Red (Low, 0–59). Accompanying copy delivers tailored training advice (e.g., "Your body is primed for high-intensity training" vs. "Prioritize active recovery and early sleep").'));

  elements.push(createSubSectionHeading('6.1.2 The Habit Streak Tracker'));
  elements.push(createBody('Directly beneath the readiness ring, the Streak Tracker visualizes behavioral consistency. It renders seven interactive day-dots representing the trailing week. Days where the daily step goal was attained render in vibrant cyan with an active checkmark; incomplete days render as muted dark slate circles. An animated flame badge displays current consecutive compliance.'));

  elements.push(createSubSectionHeading('6.1.3 The Smart Health Coach Banner'));
  elements.push(createBody('The coach banner displays actionable, deterministic insights generated by HealthCoachEngine. Priority-sorted chips (such as "Elevated Resting HR Detected" or "Bedtime Shift Advised") are presented with a one-tap dismiss action and an expandable bottom-sheet detailing physiological rationale.'));

  elements.push(createSubSectionHeading('6.1.4 The 6-Metric Health Grid & Graceful Historical Fallbacks'));
  elements.push(createBody('The core metrics grid displays six responsive cards: Steps, Calories Burned, Distance, Active Minutes, Resting Heart Rate, and Sleep Duration. Each card features a custom linear gradient, high-contrast typography, and an icon badge.'));

  elements.push(createCallout(
    'The Graceful Historical Fallback Architecture',
    'A ubiquitous flaw in standard health apps is the "morning blank state"—opening an app at 07:00 AM reveals "-- bpm" for heart rate and "0h 0m" for sleep because today data is still processing. Our dashboard implements an intelligent fallback algorithm: If today resting HR is null, the card scans recentDays to retrieve the most recent verified value (e.g., "Last recorded · 71 bpm"). If today sleep is pending, it displays "Last night · 8h 45m". The user is NEVER confronted with empty or broken placeholders.'
  ));

  elements.push(createSubSectionHeading('6.1.5 The 7-Day Steps Volume Chart & Weekly Trend Analysis'));
  elements.push(createBody('The lower half of the dashboard renders an interactive bar chart powered by FL Chart. Seven rounded bar rods illustrate daily step volume against a horizontal dashed guideline indicating the user step target (10,000 steps). Tapping any bar rod activates a floating tooltip detailing exact step counts and kilometer equivalents. A companion Weekly Trend Card calculates the volume delta between the current 7-day period and the prior 7 days, indicating progressive physical momentum.'));

  elements.push(...createFigure(
    './assets/fig3_dashboard_trends.png',
    '6.2',
    'Longitudinal Telemetry Analysis — Interactive 7-Day Pedometer Volume Bar Chart with Target Guidelines and Prior-Period Comparative Delta Card.'
  ));

  // 6.2 Heart Screen
  elements.push(createSectionHeading('6.2 Heart & Cardiovascular Intelligence Module'));
  elements.push(createBody('The Heart Screen (HeartScreen) delivers clinical-grade cardiovascular monitoring:'));

  const heartTree = 
`HeartScreen (StatefulWidget / BlocBuilder<HeartCubit, HeartState>)
  |
  +---> Scaffold
          |
          +---> SingleChildScrollView
                  |
                  +---> _HeroRestingHeartRateCard (71 BPM Hero, 93 BPM 14-Day Baseline Pill)
                  |
                  +---> _KeyBiometricsRow (HRV rMSSD, SpO2 %, Breathing Rate RPM)
                  |       * Sensor outage mitigation: Renders "--" instead of pathological 0
                  |
                  +---> _AhaZoneDistributionCard (Out of Zone, Fat Burn, Cardio, Peak Bars)
                  |
                  +---> _RestingHeartRateTrendChart (FL Chart LineChart, Bezier Smoothing)
                          * Y-axis dynamic padding [min - 5, max + 5] prevents clipping`;
  elements.push(createDiagramBlock(heartTree));

  elements.push(...createFigure(
    './assets/fig4_heart_cardiovascular.png',
    '6.3',
    'Cardiovascular Intelligence Viewport — Hero Resting Heart Rate (71 BPM), 14-Day Baseline Moving Average (93 BPM), Bezier Trend Curve, and AHA Target Heart Rate Zones.'
  ));

  elements.push(createSubSectionHeading('6.2.1 Hero Resting Heart Rate & Baseline Pill'));
  elements.push(createBody('The hero card displays Current Resting Heart Rate (e.g., 71 BPM), synchronized 1:1 with the dashboard. Adjacent to the hero value is a 14-Day Average baseline pill (e.g., 93 BPM). A dynamic delta badge indicates whether the user cardiovascular baseline is trending upward (fatigue/stress) or downward (improved aerobic efficiency).'));

  elements.push(createSubSectionHeading('6.2.2 Key Biometrics Row & Sensor Outage Handling'));
  elements.push(createBody('Three secondary biometrics are displayed in a horizontal layout: HRV rMSSD (ms), SpO2 Blood Oxygenation (%), and Breathing Rate (RPM). When optical sensors fail to record these metrics due to movement artifacts or charging, the widget displays a clean, muted "--" rather than a pathological "0", completely preventing false medical panic.'));

  elements.push(createSubSectionHeading('6.2.3 American Heart Association (AHA) Zone Distribution'));
  elements.push(createBody('A multi-segmented progress bar illustrates time spent across the four cardiovascular zones: Out of Zone (<95 BPM), Fat Burn (95–132 BPM), Cardio (133–161 BPM), and Peak (>=162 BPM). Total earned Active Zone Minutes are highlighted with an active flame badge.'));

  elements.push(createSubSectionHeading('6.2.4 14-Day Resting HR Trend Bézier Chart & Noise Elimination'));
  elements.push(createBody('An FL Chart line chart plots the 14-day resting heart rate trajectory. Dynamic Y-axis min/max padding prevents curve clipping at boundaries. Crucially, we eliminated the noisy, legacy list of 40+ raw intraday heart rate tiles that previously cluttered the bottom of the screen, focusing the user exclusively on high-value cardiovascular trends.'));

  // 6.3 Sleep Screen
  elements.push(createSectionHeading('6.3 Sleep Stage Architecture & Recovery Module'));
  elements.push(createBody('The Sleep Screen (SleepScreen) visualizes nightly restorative architecture:'));
  elements.push(createBullet('Displays the normalized sleep score (e.g., 89 · Good), total net sleep duration (8h 45m), exact bedtime (22:30), and wake-up timestamp (07:15).', 'Hero Sleep Card: '));
  elements.push(createBullet('Renders a segmented horizontal hypnogram visualizing the clinical proportion of Deep Sleep (120m), REM Sleep (95m), Light Sleep (310m), and Awake Restlessness (37m). Each stage features an educational modal explaining its physiological role.', 'Sleep Stages Hypnogram: '));
  elements.push(createBullet('Chronological list of historical sleep sessions strictly sorted by wake-up date descending, guaranteeing that the most recent night is always at the top.', 'Historical Sleep Log: '));

  elements.push(...createFigure(
    './assets/fig5_sleep_hypnogram.png',
    '6.4',
    'Polysomnography-Aligned Sleep Architecture — Calibrated 89 Sleep Score, 8h 45m Net Restorative Rest, and Clinical Stage Distribution Hypnogram.'
  ));

  // 6.4 Activity Screen
  elements.push(createSectionHeading('6.4 Activity, Physical Strain & Workout Module'));
  elements.push(createBody('The Activity Screen (ActivityScreen) logs physical movement and structured exercise:'));
  elements.push(createBullet('Visualizes 14-day rolling averages for daily steps and caloric expenditure.', 'Volume Summary Header: '));
  elements.push(createBullet('Interactive 14-day bar chart illustrating daily step distributions across the trailing two weeks.', '14-Day Step Volume Chart: '));
  elements.push(createBullet('Structured data table presenting daily step counts, total calories burned, distance traversed (km), and active exercise minutes.', 'Daily Summary Table: '));
  elements.push(createBullet('Card list detailing individual workouts (running, cycling, walking, swimming), including duration, average heart rate, and caloric burn.', 'Recent Workout Log: '));

  elements.push(...createFigure(
    './assets/fig6_activity_workouts.png',
    '6.5',
    'Physical Strain & Exercise Telemetry Viewport — 14-Day Activity Volume Distributions, Caloric Expenditure Aggregation, and Historical Daily Summary Table.'
  ));

  // 6.5 Goals & Profile
  elements.push(createSectionHeading('6.5 Authentication, Goals Configuration & User Profile Modules'));
  elements.push(createBody('The application provides intuitive target management and streamlined onboarding:'));
  elements.push(createBullet('LoginScreen delivers frictionless Google Sign-In authentication. We removed the legacy Demo Mode button to eradicate confusing admin-permission alerts, enforcing clean hardware Keystore session caching.', 'Authentication Flow: '));
  elements.push(createBullet('EditGoalsScreen provides interactive sliders allowing users to customize daily targets (Steps: 1,000–30,000; Calories: 1,000–5,000; Sleep: 4h–12h; Active Minutes: 10m–180m). Saving instantly updates Firestore and triggers immediate dashboard ring recalculation.', 'Goals Configuration: '));
  elements.push(createBullet('ProfileScreen displays user identity, Google account link status, and diagnostic sync telemetry. A Manual Force-Sync button triggers an immediate end-to-end cloud revalidation.', 'Profile & Diagnostics: '));

  elements.push(...createFigure(
    './assets/fig1_login_auth.png',
    '6.6',
    'Secure User Authentication Viewport — Streamlined Google Sign-In with Demo Mode Removed and Automated Hardware Keystore Session Restoration.'
  ));

  return elements;
}

module.exports = { getChapter6 };
