// lib/core/models/health_insight.dart

import 'package:equatable/equatable.dart';
import 'package:flutter/material.dart';
import '../../app/theme.dart';

enum InsightType {
  elevatedRhr,
  optimalRecovery,
  sleepDebt,
  readinessPacing,
  streakKeeper,
  sedentaryWarning,
}

enum InsightSeverity {
  positive,
  info,
  warning,
  caution,
}

/// A personalized health & recovery insight generated by the smart coach.
class HealthInsight extends Equatable {
  const HealthInsight({
    required this.id,
    required this.type,
    required this.severity,
    required this.title,
    required this.message,
    required this.metricTag,
    required this.icon,
    required this.accentColor,
    this.actionLabel,
  });

  final String id;
  final InsightType type;
  final InsightSeverity severity;
  final String title;
  final String message;
  final String metricTag;
  final IconData icon;
  final Color accentColor;
  final String? actionLabel;

  /// Returns a background tint color tailored for dark theme cards.
  Color get backgroundColor => accentColor.withValues(alpha: 0.12);

  /// Returns a border color matching the severity.
  Color get borderColor => accentColor.withValues(alpha: 0.28);

  static Color resolveSeverityColor(InsightSeverity severity) {
    switch (severity) {
      case InsightSeverity.positive:
        return AppTheme.activeColor; // Emerald #10B981
      case InsightSeverity.info:
        return AppTheme.distanceColor; // Cyan #22D3EE
      case InsightSeverity.warning:
        return AppTheme.calorieColor; // Amber/Orange #F97316
      case InsightSeverity.caution:
        return AppTheme.heartColor; // Crimson #EF4444
    }
  }

  @override
  List<Object?> get props => [
        id,
        type,
        severity,
        title,
        message,
        metricTag,
        icon,
        accentColor,
        actionLabel,
      ];
}
